spring.application.name=protect

spring.datasource.url=jdbc:postgresql://localhost:5432/seguranca_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port= 8081

app.frontend.url=http://localhost:4200


spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=b86d4a6c86f768
spring.mail.password=48b531168ab525
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


server.ssl.enabled=true


server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=123456
server.ssl.key-store-type=pkcs12
server.ssl.key-alias=protect-api

server.http2.enabled=true