spring.application.name=protect

spring.datasource.url=jdbc:postgresql://localhost:5432/seguranca_db
spring.datasource.username=postgres
spring.datasource.password=2302123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port= 8081


spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=47fed51906dec2
spring.mail.password=3f384caf81cb0c
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true